### ISSUE TITLE
Test Debug - fork.c/forkandopen.c

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#153]
per [150](https://github.com/Lind-Project/lind_project/issues/150)

It seems like theres fd table replication issues on fork. Both of these are failing immediately after fork when trying to pen runnable-ld.so

```
[1760,3685512768:13:24:20.307099] [nap 1] new child count: 1
[1760,3685512768:13:24:20.307102] fork_num = 1, cage_id = 2
[1760,3685512768:13:24:20.307105] NaClHostDescOpen(0x55e4c1343660, /lib/glibc/runnable-ld.so, 0x0, 0x1b6)
[1760,3685512768:13:24:20.307108] NaClHostDescOpen: invoking POSIX open(/lib/glibc/runnable-ld.so,0x0,0600)
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/safeposix/dispatcher.rs:90:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/003d8d3f56848b6f3833340e859b089a09aea36a/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/003d8d3f56848b6f3833340e859b089a09aea36a/library/core/src/panicking.rs:100:14
   2: core::panicking::panic
             at /rustc/003d8d3f56848b6f3833340e859b089a09aea36a/library/core/src/panicking.rs:50:5
   3: dispatcher
   4: lind_open
             at /home/lind/lind_project/src/native_client/src/shared/platform/lind_platform.c:117:5
   5: NaClHostDescOpen
             at /home/lind/lind_project/src/native_client/src/shared/platform/posix/nacl_host_desc.c:314:15
   6: NaClDescIoDescOpen
             at /home/lind/lind_project/src/native_client/src/trusted/desc/nacl_desc_io.c:187:12
   7: NaClAppLoadFileFromFilename
             at /home/lind/lind_project/src/native_client/src/trusted/service_runtime/load_file.c:23:28
   8: NaClChildNapCtor
             at /home/lind/lind_project/src/native_client/src/trusted/service_runtime/nacl_app_thread.c:113:22
   9: NaClSysFork
             at /home/lind/lind_project/src/native_client/src/trusted/service_runtime/nacl_syscall_common.c:4081:15
  10: NaClSysForkDecoder
             at /home/lind/lind_project/src/native_client/scons-out/dbg-linux-x86-64/gen/native_client/src/trusted/service_runtime/nacl_syscall_handlers.c:4692:10
  11: NaClSyscallCSegHook
             at /home/lind/lind_project/src/native_client/src/trusted/service_runtime/nacl_syscall_hook.c:149:15
  12: <unknown>
             at /home/lind/lind_project/src/native_client/src/trusted/service_runtime/arch/x86_64/nacl_syscall_64.S:211
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
```

**Comment by rennergade** [comment]
I fixed the fork bug with the last PR.

forkandopen now works, but I found some weird behavior with fork.c

Namely we get a dup error, even though dup isnt called in the program! And something triggers a waitpid perrror. May be related.

```Error in syscall: dup or dup2 - EACCES: can't dup the provided file
waitpid(): No child processes```

**Comment by rennergade** [comment]
Ok so that waitpid perror is just because the child is exiting first and isnt an actual error. I fixed the dup problm in a PR over on the rustposix repo.
