### ISSUE TITLE
Dependancy on old make and texinfo versions

### ISSUE THREAD

**Issue by alyptik** [Lind-Project/lind_project#2]
Currently we are depending on older versions of `make` and `texinfo` which we have had to vendor. This is due to build errors in the glibc part of our toolchain when uses more recent versions. At some point it would be helpful to patch glibc or find some other solution which more ideal than this.

**Comment by rennergade** [comment]
I've been able to fix many problems with the "native" build by doing  the following:

1. Replace `nacl-binutils` with latest nacl release
2. Replace `nacl-gcc` with latest nacl release
3. Update `native_client/tools/Makefile` to have no texinfo for pregcc-standalone via `MAKEINFO=missing`
4. Add -fgnu89-inline to GCC_CC in `native_client/tools/Makefile`
5. Update glibc using `sed "s/3\.\[89\]/3\.\[89\]\* | 4/" -i configure` on configure file to update Make version check

**Comment by rennergade** [comment]
I am however now failing in the glibc build during the python script `nacl_fixup_ldso.py` while getting a mysterious Assert error. I'm amiss to what's causing this.

```
python2 nacl_fixup_ldso.py $LIND_PREFIX/lind_project/native_client/tools/BUILD/build-glibc32/elf/runnable-ld.so.tmp
Traceback (most recent call last):
  File "nacl_fixup_ldso.py", line 63, in <module>
    main(sys.argv[1:])
  File "nacl_fixup_ldso.py", line 51, in main
    check("H", offset_e_phnum32, 7)
  File "nacl_fixup_ldso.py", line 36, in check
    raise AssertionError("Expected %s, got %s" % (expected, got))
AssertionError: Expected 7, got 9
Makefile:342: recipe for target '$LIND_PREFIX/lind_project/native_client/tools/BUILD/build-glibc32/elf/runnable-ld.so' failed
make[5]: *** [$LIND_PREFIX/lind_project/native_client/tools/BUILD/build-glibc32/elf/runnable-ld.so] Error 1
make[5]: Leaving directory '$LIND_PREFIX/lind_project/lind_glibc/elf'
Makefile:207: recipe for target 'elf/subdir_lib' failed
make[4]: *** [elf/subdir_lib] Error 2
make[4]: Leaving directory '$LIND_PREFIX/lind_project/lind_glibc'
Makefile:12: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '$LIND_PREFIX/lind_project/native_client/tools/BUILD/build-glibc32'
Makefile:663: recipe for target 'BUILD/stamp-glibc32' failed
make[2]: *** [BUILD/stamp-glibc32] Error 2
make[2]: Leaving directory '$LIND_PREFIX/lind_project/native_client/tools'
Makefile:955: recipe for target 'build-with-glibc' failed
make[1]: *** [build-with-glibc] Error 2
make[1]: Leaving directory '$LIND_PREFIX/lind_project/native_client/tools'
```

**Comment by rennergade** [comment]
This seemingly could be due to a non-updated `native_client` repository.

Per Brendan, using read-elf or obj-dump here against a working version would be helpful at examining this error.
