### ISSUE TITLE
Add Semaphores to RustPOSIX

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#321]
We're zeroing in on what seems like the remaining postgres bug and it seems like it revolves around POSIX semaphores, though were still working out if its caused by a prior condition or the semaphores themselves.

Regardless, we haven't really touched these since the initial migration from nacl. The nacl team implemented these with wrappers in libc around mutex/condvars. This may pose a problem for shared memory based semaphore since libc isn't persisted.

@Yaxuan-w is going to implement these in RustPOSIX while I hook them in to libc/nacl.

Overall design:
Create RustSemaphore, our semaphore implementation struct
Add semaphore table to cage struct: Dashmap of 32bit ptr cast to int -> Semaphore struct  <i32, RustSemaphore>

Rust semaphore should just have a value field which is atomici32, and a atomicbool field to tell if its shared

sem_init will create the struct, init the value, and add it to semaphore table
sem_post will update value
sem_wait will decrement value, wait if 0 - waiting should just be done with a while loop that checks value, we should yield the thread in the loop to conserve resources.
sem_destroy will remove semaphore

if semaphore is created as shared, it should persist to children on fork, but not persist on exec

We'll also have to handle full shared memory cases but lets start with this for now.

**Comment by rennergade** [comment]
@Yaxuan-w  is going to start by making tests for shared sem fork and a test for two processes using semaphores with shmat etc. so we can understand semantics

**Comment by rennergade** [comment]
Ok. Thanks to @Yaxuan-w who put together a base implementation of Semaphores in RustPOSIX. I extended this to working with shared memory which was a bit difficult. @RusherRG has run some tests on this and we're passing both a fork and shared memory example. So we're very close here.

A couple more things I'd like to test/fix

- I think theres a bug when sem_destroy and shmdt are used in the same example. We currently remove a semaphor if its in a shared memory region which is detached, but im not sure thats always the correct behavior ie in the cage where sem_init was actually called. Can we test this natively and read the man pages to get this correct? @RusherRG 
- We haven't tested mixing forked shared semaphores and sysv shm shared semaphores. I think we need to do a test that mixes the two @RusherRG . There may be a bug about book keeping when we fork a sysv semaphore.
- I'd like to extend the two cage example to working with 3 cages, I think once we get to three we can reason that it will extended to multiple cages correctly.

**Comment by rennergade** [comment]
We also should implement sem_trywait and sem_timedwait but aren't urgent

**Comment by RusherRG** [comment]
Considering now most of the semaphore issues that we encountered while testing Postgres are resolved, I tried to compile and run the entire LAMP stack to check whether everything works together as a whole. Postgres and Nginx seem to be initialized and setup successfully but the initialization of Gunicorn threw an error.

 ```
[2023-09-20 20:23:11 +0000] [25] [INFO] Starting gunicorn 19.10.0
[2023-09-20 20:23:11 +0000] [25] [INFO] Listening at: http://0.0.0.0:8000 (25)
[2023-09-20 20:23:11 +0000] [25] [INFO] Using worker: sync
sem_wait: Invalid argument
sem_post: Invalid argument
sem_wait: Invalid argument
sem_post: Invalid argument
sem_wait: Invalid argument
sem_post: Invalid argument
sem_wait: Invalid argument
[2023-09-20 20:23:11 +0000] [30] [INFO] Booting worker with pid: 30
sem_wait: Invalid argument
[2023-09-20 20:23:11 +0000] [30] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 584, in spawn_worker
    self.log.info("Booting worker with pid: %s", worker.pid)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/glogging.py", line 271, in info
    self.error_log.info(msg, *args, **kwargs)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1132, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1250, in _log
    self.handle(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1260, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1300, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 746, in handle
    self.release()
  File "/usr/local/lib/python2.7/logging/__init__.py", line 700, in release
    self.lock.release()
  File "/usr/local/lib/python2.7/threading.py", line 143, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
sem_wait: Invalid argument
[2023-09-20 20:23:11 +0000] [30] [INFO] Worker exiting (pid: 30)
sem_wait: Invalid argument
[2023-09-20 20:23:11 +0000] [30] [INFO] Unhandled exception in main loop
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 203, in run
    self.manage_workers()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 548, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 619, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 602, in spawn_worker
    self.log.info("Worker exiting (pid: %s)", worker.pid)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/glogging.py", line 271, in info
    self.error_log.info(msg, *args, **kwargs)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1132, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1250, in _log
    self.handle(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1260, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1300, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 746, in handle
    self.release()
  File "/usr/local/lib/python2.7/logging/__init__.py", line 700, in release
    self.lock.release()
  File "/usr/local/lib/python2.7/threading.py", line 143, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock

Error: cannot release un-acquired lock

gunicornexec.py
```

I am trying to trace the issue and try to fix the bug. Seems like it could be something related to bad initialization of the semaphore as `sem_post` and `sem_wait` just take one argument which is the semaphore handle itself.
