### ISSUE TITLE
Log Based FS Issue

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#339]
Issue 1: Socket Inodes
There seems to be an issue thats popping up in socketpair where a previous socket inode is persisting between runs causing an error. More details to be added by @RusherRG 

Issue 2: FS Issue
We've seen another logging issue come up when exiting early. More details to be added by @RusherRG

**Comment by yizhuoliang** [comment]
Okay so it's surprising that, with every branch up-to-date on develop, `make test`'s `socketpair.c` test has a 30% chance of failing. No need to twist anything for reproducing this, the test simply fails.

**Comment by RusherRG** [comment]
## Socket Inodes Issue

While I was running the lamp stack tests I encountered the following error:
```
@(1:312) $ rr record ../bin/sel_ldr -a -- runnable-ld.so --library-path /lib/glibc /bin/bash run_lamp.sh
rr: Saving execution to trace directory `/home/lind/.local/share/rr/sel_ldr-102'.
[1262891,3930392704:17:07:14.761068] BYPASSING ALL ACL CHECKS
thread '<unnamed>' panicked at src/safeposix/syscalls/net_calls.rs:1959:40:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/panicking.rs:127:5
   3: core::option::Option<T>::unwrap
             at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/option.rs:925:21
   4: rustposix::safeposix::syscalls::net_calls::<impl rustposix::safeposix::cage::Cage>::socketpair_syscall
             at /home/lind/lind_project/src/safeposix-rust/src/safeposix/syscalls/net_calls.rs:1959:9
   5: rustposix::safeposix::dispatcher::dispatcher::{{closure}}
             at /home/lind/lind_project/src/safeposix-rust/src/safeposix/dispatcher.rs:146:22
   6: dispatcher
             at /home/lind/lind_project/src/safeposix-rust/src/safeposix/dispatcher.rs:396:13
   7: lind_socketpair
             at /home/lind/lind_project/src/native_client/src/shared/platform/lind_platform.c:268:5
   8: NaClSysSocketPair
             at /home/lind/lind_project/src/native_client/src/trusted/service_runtime/nacl_syscall_common.c:2441:12
   9: NaClSysSocketPairDecoder
             at /home/lind/lind_project/src/native_client/scons-out/dbg-linux-x86-64/gen/native_client/src/trusted/service_runtime/nacl_syscall_handlers.c:3588:10
  10: NaClSyscallCSegHook
             at /home/lind/lind_project/src/native_client/src/trusted/service_runtime/nacl_syscall_hook.c:175:15
  11: <unknown>
             at /home/lind/lind_project/src/native_client/src/trusted/service_runtime/arch/x86_64/nacl_syscall_64.S:221
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5

** Signal 6 from trusted code: pc=7f4dea4ed36c
```

This error occurs when I setup the entire lamp-stack starting postgres, initializing postgres, starting nginx and gunicorn; once everything is up and running if I exit the process using `CTRL + c` and then run the lamp stack again without resetting the lind filesystem. The error indicates that the socket inode hasn't been removed cleanly when the process is killed resulting in the next startup being unable to create a socketpair on the same UNIX socket.

In order to recreate the issue, one can checkout the [lamp-stack-tests](https://github.com/Lind-Project/lind_project/tree/lamp-stack-tests) branch and use the scripts present in `tests/lamp-stack-tests/profiling`

```
cd tests/lamp-stack-tests/profiling
./lind_setup.sh

CTRL + c (once everything is running)

lind /bin/bash run_lamp.sh (running this should result in error, if not try running it a couple of times)
```

**Comment by rennergade** [comment]
This seemed to also be fixed by https://github.com/Lind-Project/lind_project/issues/343

Closing for now
