### ISSUE TITLE
Accept-Inet Rust Panic!

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#342]
There seems to be a panic caused in nginx due to trying to unwrap() a None option coming from the pending_conn_table.

@RusherRG can you provide additional details

**Comment by RusherRG** [comment]
```
let (acceptedresult, remote_addr) = if let Some(mut vec) = NET_METADATA.pending_conn_table.get_mut(&sockhandle.localaddr.unwrap().port()) {
      //if we got a pending connection in select/poll/whatever, return that here instead
      let tup = vec.pop().unwrap(); //pending connection tuple recieved
      if vec.is_empty() {
          drop(vec);
          NET_METADATA.pending_conn_table.remove(&sockhandle.localaddr.unwrap().port()); //remove port from pending conn table if no more pending conns exist for it
      }
      tup
  }
```

The above snippet is from the function `accept_inet` in `src/safeposix/syscalls/net_call.rs`. The error occurs on the line `let tup = vec.pop().unwrap();`

**Comment by RusherRG** [comment]
Following is the backtrace of the error

```
thread '<unnamed>' panicked at src/safeposix/syscalls/net_calls.rs:1131:41:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7f1f7ce3bd7c - std::backtrace_rs::backtrace::libunwind::trace::h461fbefb027ec110
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f1f7ce3bd7c - std::backtrace_rs::backtrace::trace_unsynchronized::h50c0d00febf4cf37
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1f7ce3bd7c - std::sys_common::backtrace::_print_fmt::hc2adc9e782f93fbb
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f1f7ce3bd7c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf109171ae79d32b1
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f1f7ce61890 - core::fmt::rt::Argument::fmt::hb783c6fd4c68805d
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/fmt/rt.rs:142:9
   5:     0x7f1f7ce61890 - core::fmt::write::h9b8906fd60d61b90
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/fmt/mod.rs:1117:17
   6:     0x7f1f7ce39b9f - std::io::Write::write_fmt::h940a35bcd59aa63d
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/io/mod.rs:1762:15
   7:     0x7f1f7ce3bb64 - std::sys_common::backtrace::_print::h6af4f743eba33b3b
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f1f7ce3bb64 - std::sys_common::backtrace::print::h16acb5b2d5fe90a7
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f1f7ce3d317 - std::panicking::default_hook::{{closure}}::hd2766c85b5f69646
  10:     0x7f1f7ce3d07f - std::panicking::default_hook::hd7352be88f308fd4
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panicking.rs:292:9
  11:     0x7f1f7ce3d798 - std::panicking::rust_panic_with_hook::h84b1df6311265f63
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panicking.rs:731:13
  12:     0x7f1f7ce3d649 - std::panicking::begin_panic_handler::{{closure}}::hb5b46a0fb17cc9d6
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panicking.rs:601:13
  13:     0x7f1f7ce3c246 - std::sys_common::backtrace::__rust_end_short_backtrace::h8d1a3272d720bdec
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x7f1f7ce3d3e2 - rust_begin_unwind
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panicking.rs:597:5
  15:     0x7f1f7cc28cd5 - core::panicking::panic_fmt::h76d60a2d79b08002
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/panicking.rs:72:14
  16:     0x7f1f7cc28d73 - core::panicking::panic::h7169440dafcc5823
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/panicking.rs:127:5
  17:     0x7f1f7cd8c616 - core::option::Option<T>::unwrap::h0bf88b141a5685fe
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/option.rs:925:21
  18:     0x7f1f7ccd40e3 - rustposix::safeposix::syscalls::net_calls::<impl rustposix::safeposix::cage::Cage>::accept_inet::h9fd1fdde3a716112
                               at /home/lind/lind_project/src/safeposix-rust/src/safeposix/syscalls/net_calls.rs:1131:31
  19:     0x7f1f7ccd27f1 - rustposix::safeposix::syscalls::net_calls::<impl rustposix::safeposix::cage::Cage>::accept_syscall::h8bdc6383b5c5b629
                               at /home/lind/lind_project/src/safeposix-rust/src/safeposix/syscalls/net_calls.rs:1027:54
  20:     0x7f1f7cd91e04 - rustposix::safeposix::dispatcher::dispatcher::{{closure}}::h09b771e576053254
                               at /home/lind/lind_project/src/safeposix-rust/src/safeposix/dispatcher.rs:138:22
  21:     0x7f1f7cc7970a - dispatcher
                               at /home/lind/lind_project/src/safeposix-rust/src/safeposix/dispatcher.rs:317:26
  22:     0x5578a67bc76f - lind_accept
                               at /home/lind/lind_project/src/native_client/src/shared/platform/lind_platform.c:230:5
  23:     0x5578a6759939 - NaClSysAccept
                               at /home/lind/lind_project/src/native_client/src/trusted/service_runtime/nacl_syscall_common.c:4573:9
  24:     0x5578a675d7b1 - NaClSysAcceptDecoder
                               at /home/lind/lind_project/src/native_client/scons-out/dbg-linux-x86-64/gen/native_client/src/trusted/service_runtime/nacl_syscall_handlers.c:2530:10
  25:     0x5578a677a080 - NaClSyscallCSegHook
                               at /home/lind/lind_project/src/native_client/src/trusted/service_runtime/nacl_syscall_hook.c:175:15
  26:     0x5578a676de9b - <unknown>
                               at /home/lind/lind_project/src/native_client/src/trusted/service_runtime/arch/x86_64/nacl_syscall_64.S:221
fatal runtime error: failed to initiate panic, error 5

** Signal 6 from trusted code: pc=7f1f7c54b36c
```

**Comment by rennergade** [comment]
@RusherRG can you provide some additional context on how to trigger this bug? Is it possible to trigger running nginx without the rest of the lamp stack?

**Comment by RusherRG** [comment]
We can recreate this error using the following steps:
1. Using the following branches
a. lind_project - lamp-stack-tests
b. safeposix_rust - signal-domsock
c. lind_glibc - sigaction-merge
d. native_client - sigaction-merge
2.  Go to `tests/lamp_stack/profiling/` and run `./lind_setup.sh`. This will setup the lamp stack
3. Open a new shell session and send a request using
a. `curl http://localhost:80` (might have to run multiple times) or
b. `wrk -t 1 -c 1 -d 60 --timeout 60 http://localhost:80`

**Comment by rennergade** [comment]
fixed by @yizhuoliang thanks!
