### ISSUE TITLE
Fix gunicorn error

### ISSUE THREAD

**Issue by RusherRG** [Lind-Project/lind_project#372]
When we setup LAMP stack in Lind and send requests using the wrk program, we see the following error trace at the end of every wrk run. 
```
[2024-05-02 22:09:58 +0000] [28] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 191, in handle_request
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
    resp.write(item)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 335, in write
    self.send_headers()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 331, in send_headers
    util.write(self.sock, util.to_bytestring(header_str, "latin-1"))
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 304, in write
    sock.sendall(data)
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 11] Resource temporarily unavailable
```

**Comment by rennergade** [comment]
I fixed this by implementing EPIPE for domain sockets on send, will close on latest merge
